global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flaskapp'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
